### PR TITLE
build: add Semantic PR linter

### PR DESCRIPTION
**Pull request by hanno-marcelkalveram**
Adding this here from the [templates at `wearehanno/.github`](https://github.com/wearehanno/.github)

### CODE REVIEW

**Comment by hanno-jonlay** [comment]
I don't see any major issues here, but since we have an open conversation about bumping the version that action, would it make sense to resolve that before merging this one (and then needing to raise another PR right afterwards to bump once again)?

**Comment by hanno-marcelkalveram** [comment]
`3.2.6` seems to work. I've updated this accordingly.

**Comment by hanno-jonlay** [comment]
@hanno-marcelkalveram since the upgrade resolves the duplicate Action run, I have:

1. Removed the corresponding comment: https://github.com/wearehanno/action-semantic-release/pull/9/commits/4073f5db0c990ac69b7b2d3729fa5888228ed261
2. Replicated the version bump and change on the action-semantic-release: https://github.com/wearehanno/.github/commit/19ecbff859353a04a17948ab16e562f704f0958a

LGTM

**Review by hanno-jonlay — APPROVED** [review]

**Comment by hanno-jonlay** [comment]
It's perhaps also worth mentioning that while I haven't checked this, I think that this comment (https://github.com/wearehanno/action-semantic-release/blob/hanno-marcelkalveram-patch-1/.github/workflows/pr.yml#L4) might be resolved by https://github.com/amannn/action-semantic-pull-request/releases/tag/v3.0.0

So if you were to validate that inside another repository, to confirm that the action doesn't run while a PR is in **Draft**, we might also be able to remove this line from the workflow and clean things up further?

**Comment by hanno-marcelkalveram** [comment]
> 2. Replicated the version bump and change on the action-semantic-release: [wearehanno/.github@19ecbff](https://github.com/wearehanno/.github/commit/19ecbff859353a04a17948ab16e562f704f0958a)

I was just going to update this as well 😄

**Pull request merged**
