### PR TITLE
build: remove installing deps from job

### PR DESCRIPTION
**Pull request by hanno-marcelkalveram**
I realised that the dependencies here get added to the package being released. Makes sense because we're using `yarn add` in the repo directory.

 There are two ways to prevent this from happening:
- try installing them as dependencies of the action (that's what I'm trying here)
- install them as `devDependencies` (adding the `-D` flag)

It'll probably be the latter, but I find the former slightly more elegant. I'll try that out with the help of this branch now.

### CODE REVIEW

**Comment by hanno-marcelkalveram** [comment]
@hanno-jonlay this approach works.

Screenshot 2021-01-27 at 13 25 10

Looks like the action's dependencies can just live inside `package.json` and it automatically installs them, similar to how GH actions work: https://github.com/actions/toolkit/blob/main/packages/github/package.json#L40

It's still not documented clearly anywhere _how_ GH installs those actions, but it seems to be using `npx`.

**Review by hanno-jonlay — APPROVED** [review]
Big fan of this approach, if indeed it works as you think it does.

Nice work!

**Comment by hanno-jonlay** [comment]
@hanno-marcelkalveram just double-check that you definitely want this to be `build:` commit. IIRC you would have resolved this so that it now correctly produces a release, right?

**Comment by hanno-marcelkalveram** [comment]
> @hanno-marcelkalveram just double-check that you definitely want this to be `build:` commit. IIRC you would have resolved this so that it now correctly produces a release, right?

It should, yeah! Let's see.

**Comment by hanno-jonlay** [comment]
@hanno-marcelkalveram just in case you didn't spot this, the build failed upon merge into `main`.

You might have pinged me about this elsewhere - apologies if so!

**Comment by hanno-marcelkalveram** [comment]
What a mess! I tested this in my private package, and it worked. Only now I realised that the packages were made available through the faulty `eslint-config`. That's why it didn't fail there, but did fail here 👎 

I'll create a new PR now with the other approach (`devDependencies`) which hopefully should resolve this.

**Pull request merged**
